// layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./AuthContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <AuthProvider>
          {children}  {/* This will include everything inside the pages (including Home page) */}
        </AuthProvider>
      </body>
    </html>
  );
}
