// import type { Metadata } from "next";
// import "./globals.css";
// import { AuthProvider } from "./AuthContext";
// import { monsieurClass } from "./styles/fontSwitcher"; // Your custom font import

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={monsieurClass}> {/* Add the font class here */}
//       <body>
//         <AuthProvider>{children}</AuthProvider>
//       </body>
//     </html>
//   );
// }

import Providers from "./Providers";
import type { Metadata } from "next";
import "./globals.css";
import { monsieurClass } from "./styles/fontSwitcher";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={monsieurClass}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
